### ISSUE TITLE
Bug: Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped."

### ISSUE THREAD

**Issue by codykonior** [proxb/PoshRSJob#163]
If you stop and remove jobs before they naturally finish, it often destroys the pipeline and prevents any further batched jobs during that PS session.

``` powershell
# Likely not responsible but this is my environment
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Normal
1..5 | Start-RSJob { Start-Sleep -Seconds 5 }
Get-RSJob | Wait-RSJob | Receive-RSJob

# Abort these jobs
1..5 | Start-RSJob { Start-Sleep -Seconds 5 }
Start-Sleep -Seconds 1
Get-RSJob | Stop-RSJob
Get-RSJob | Remove-RSJob

# These will now fail
1..5 | Start-RSJob { Start-Sleep -Seconds 5 }
Get-RSJob | Wait-RSJob | Receive-RSJob
```
> Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped." (repeated 25 times)

You may need to start a new session a few times in order to trigger this as sometimes the first run just works.

I've also had success in running it once successfully, then running it again in the same session and triggering the failure (with still only 25 errors output).

The errors appears to occur INSIDE the job. The Retrieve-RSJob is what shows them to the output. So the local $error will still be clear.

> HasMoreData    : False
> State          : Completed
> HasErrors      : False
> Verbose        : 
> Debug          : 
> Warning        : 
> Progress       : 
> Name           : Job86
> ID             : 86
> InputObject    : 1
> InstanceID     : 61328ca0-307f-486d-b729-71d323064e6c
> Handle         : System.Management.Automation.PowerShellAsyncResult
> Runspace       : 
> InnerJob       : System.Management.Automation.PowerShell
> Finished       : System.Threading.ManualResetEvent
> Command        :  Start-Sleep -Seconds 5 
> Error          : {Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped.", Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped.", Exception calling "EndInvoke" with "1" 
>                  argument(s): "The pipeline has been stopped.", Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped."...}
> Output         : 
> RunspacePoolID : a46f90db-afce-47b3-bf80-e076224759b8
> Completed      : True
> Batch          : a46f90db-afce-47b3-bf80-e076224759b8

So I believe this is something to do with stopping a job, an error being recorded inside the job, and the Remove-RSJob then not removing the job properly?

*Which versions of Powershell and which OS are affected by this issue? Did this work in previous versions of our scripts?**

PS 5.1
Module version 1.7.3.10 and 1.7.3.11.

**Comment by MVKozlov** [comment]
Can't reproduce it on latest version (1.7.3.11)
may be I'm fixed it then :)

**Comment by codykonior** [comment]
Confirmed, this seems fixed in 1.7.3.11.

**Comment by codykonior** [comment]
I just upgraded to the current build, 1.7.3.11, in this repository, and it's still there. I'm not sure what the differences between your setup and mine are but...

* Running in strict mode?
* ErrorAction = Stop
* Remove the $error.clear() from Line 166 of PoshRSJob.psm1 because I don't want to hide any issues.

**Comment by codykonior** [comment]
Hi @MVKozlov I've updated the bug description. It's still in the current version in this repository, unless you're referring to your own repository.

**Comment by MVKozlov** [comment]
Can reproduce it with another code
``` powershell
PS C:\> 1..5 | Start-RSJob { 1..1000000 | %{ $_* $_ | Out-Null } }

Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
106      Job106               Running         False        False         1..1000000 | %{ $_* $_ | Out-Null }
107      Job107               Running         False        False         1..1000000 | %{ $_* $_ | Out-Null }
108      Job108               Running         False        False         1..1000000 | %{ $_* $_ | Out-Null }
109      Job109               Running         False        False         1..1000000 | %{ $_* $_ | Out-Null }
110      Job110               Running         False        False         1..1000000 | %{ $_* $_ | Out-Null }


PS C:\> Get-RSJob | Stop-RSJob
PS C:\> Get-RSJob

Id       Name                 State           HasMoreData  HasErrors    Command
--       ----                 -----           -----------  ---------    -------
106      Job106               Stopped         False        True          1..1000000 | %{ $_* $_ | Out-Null }
107      Job107               Stopped         False        True          1..1000000 | %{ $_* $_ | Out-Null }
108      Job108               Stopped         False        True          1..1000000 | %{ $_* $_ | Out-Null }
109      Job109               Stopped         False        True          1..1000000 | %{ $_* $_ | Out-Null }
110      Job110               Stopped         False        True          1..1000000 | %{ $_* $_ | Out-Null }


PS C:\> Get-RSJob | Receive-RSJob
Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped."
Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped."
Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped."
Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped."
Exception calling "EndInvoke" with "1" argument(s): "The pipeline has been stopped."
```
But I'm not sure, is it RSJob bug or misunderstanding. how runspaces work ?
You `Stop` the job, so it now in 'stopped' `inconsistent!` state. May be you should not try to receive something from stopped job ? and may be we just need to deny receiving data from stopped job in the code ?

**Comment by MVKozlov** [comment]
But I still can't see that
`it often destroys the pipeline and prevents any further batched jobs during that PS session.`
After I removed stopped jobs I still can start new jobs , await for it and receive my data

**Comment by codykonior** [comment]
I can't reproduce this anymore on the current build.
